export const CRF_TEMPLATES = {
  demographics: {
    label: "Demographics CRF",
    fields: [
      { label: "Subject Identifier", type: "Char" },
      { label: "Date of Birth", type: "Date" },
      { label: "Sex", type: "Char", codelist: "Male, Female, Unknown" },
      { label: "Race", type: "Char", codelist: "White, Black or African American, Asian, Other, Multiple" },
      { label: "Ethnicity", type: "Char", codelist: "Hispanic or Latino, Not Hispanic or Latino, Not Reported, Unknown" },
      { label: "Country", type: "Char" },
      { label: "Date of Informed Consent", type: "Date" },
      { label: "Age at Screening", type: "Num" },
    ],
  },
  vitals: {
    label: "Vital Signs CRF",
    fields: [
      { label: "Vital Signs Date", type: "Date" },
      { label: "Vital Signs Time", type: "Time" },
      { label: "Systolic Blood Pressure (mmHg)", type: "Num" },
      { label: "Diastolic Blood Pressure (mmHg)", type: "Num" },
      { label: "Heart Rate (bpm)", type: "Num" },
      { label: "Body Temperature (C)", type: "Num" },
      { label: "Respiratory Rate (breaths/min)", type: "Num" },
      { label: "Weight (kg)", type: "Num" },
      { label: "Height (cm)", type: "Num" },
      { label: "Position", type: "Char", codelist: "Supine, Sitting, Standing" },
    ],
  },
  adverse_events: {
    label: "Adverse Events CRF",
    fields: [
      { label: "Adverse Event Term (Verbatim)", type: "Char" },
      { label: "AE Start Date", type: "Date" },
      { label: "AE End Date", type: "Date" },
      { label: "Severity", type: "Char", codelist: "Mild, Moderate, Severe" },
      { label: "Serious?", type: "Char", codelist: "Yes, No" },
      { label: "Causality (Relationship to Study Drug)", type: "Char" },
      { label: "Action Taken with Study Drug", type: "Char" },
      { label: "Outcome", type: "Char" },
      { label: "SAE Criteria Met", type: "Char" },
    ],
  },
  conmeds: {
    label: "Concomitant Medications CRF",
    fields: [
      { label: "Medication Name (Generic)", type: "Char" },
      { label: "ATC Code", type: "Char" },
      { label: "Indication", type: "Char" },
      { label: "Dose", type: "Num" },
      { label: "Dose Unit", type: "Char", codelist: "mg, mcg, mL, IU, g" },
      { label: "Route", type: "Char" },
      { label: "Frequency", type: "Char" },
      { label: "Start Date", type: "Date" },
      { label: "End Date", type: "Date" },
      { label: "Ongoing?", type: "Char", codelist: "Yes, No" },
    ],
  },
  labs: {
    label: "Lab Results CRF",
    fields: [
      { label: "Lab Test Name", type: "Char" },
      { label: "Lab Test Code (LOINC)", type: "Char" },
      { label: "Specimen Collection Date", type: "Date" },
      { label: "Result (Original Units)", type: "Num" },
      { label: "Original Units", type: "Char" },
      { label: "Result (Standard Units)", type: "Num" },
      { label: "Standard Units", type: "Char" },
      { label: "Normal Range Low", type: "Num" },
      { label: "Normal Range High", type: "Num" },
      { label: "Clinical Significance", type: "Char" },
      { label: "Fasting Status", type: "Char", codelist: "Yes, No" },
    ],
  },
  medical_history: {
    label: "Medical History CRF",
    fields: [
      { label: "Medical History Term (Verbatim)", type: "Char" },
      { label: "Condition Start Date", type: "Date" },
      { label: "Condition End Date", type: "Date" },
      { label: "Condition Ongoing?", type: "Char", codelist: "Yes, No" },
      { label: "Medical History Category", type: "Char" },
      { label: "Body System", type: "Char" },
      { label: "History Location", type: "Char" },
    ],
  },
  disposition: {
    label: "Disposition CRF",
    fields: [
      { label: "Disposition Event", type: "Char", codelist: "Completed, Adverse Event, Withdrawal by Subject, Lost to Follow-up, Death" },
      { label: "Discontinuation Date", type: "Date" },
      { label: "Disposition Category", type: "Char" },
      { label: "Disposition Epoch", type: "Char", codelist: "Screening, Treatment, Follow-up" },
    ],
  },
  subject_characteristics: {
    label: "Subject Characteristics CRF",
    fields: [
      { label: "Subject Characteristic Name", type: "Char" },
      { label: "Characteristic Result", type: "Char" },
      { label: "Characteristic Date", type: "Date" },
    ],
  },
};
